name: Generate Snake Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Chạy hàng ngày lúc 00:00 UTC
  workflow_dispatch:     # Cho phép chạy thủ công

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
          git add dist/snake.svg
          git commit -m "Updated Snake Contribution Graph 🐍" || echo "No changes to commit"
          git push origin main
